---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  annotations:
    autoscaling.knative.dev/minScale: "1"
  labels:
    apps.tanzu.vmware.com/workload-type: web
  name: spring-petclinic-rest
  namespace: default
spec:
  env:
  - name: "BP_MAVEN_BUILD_ARGUMENTS"
    value: "-Dmaven.test.skip=false package"
  source:
    git:
      ref:
        branch: master
      url: https://github.com/tfynes-pivotal/spring-petclinic-rest
